kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: noderedstorage-claim
  namespace: homeautomation
spec:
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
