apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb
  namespace: homeautomation
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
status:
  loadBalancer: {}
