kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdbstorage-claim
  namespace: homeautomation
spec:
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
