apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb
  namespace: homeautomation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
    spec:
      containers:
      - image: docker.io/influxdb:1.7.6
        name: influxdb
        resources: {}
        envFrom:
        - secretRef:
            name: influxdb-creds
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: var-lib-influxdb
      volumes:
      - name: var-lib-influxdb
        persistentVolumeClaim:
          claimName: influxdbstorage-claim
