apiVersion: v1
data:
  INFLUXDB_DATABASE: c2Vuc29yZGF0YQ==
  INFLUXDB_HOST: aW5mbHV4ZGI=
  INFLUXDB_PASSWORD: cm9vdA==
  INFLUXDB_USERNAME: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: influxdb-creds
  namespace: homeautomation
