apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdbstorage
  namespace: homeautomation
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /volume1/kubestorage/influxdb
    server: 192.168.2.100
